services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    volumes:
      - ../temp:/app/temp
      - ../output:/app/output
      - ../logs:/app/logs
    command: python app/main.py

  redis:
    image: docker.arvancloud.ir/redis:7-alpine
    container_name: newspaper_redis
    ports:
      - "6379:6379"
